### PR TITLE
fix that table queuedtasks was removed in ownCloud 8.1.0

### LINKED ISSUE #90: oc_queuedtasks doesn't exist but is accessed
I just upgraded from 8.0.5 to 8.1 and wanted to enable search_lucene again. However, the upgrade of serach_lucene tries to access oc_queuedtasks which is deprecated according to https://doc.owncloud.com/server/8.0/ownCloudServerAdminManual.pdf and not existing on my system any more.

```
Updating <search_lucene> ...
Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'DELETE FROM `oc_queuedtasks` WHERE `app`=?' with params ["search_lucene"]:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_queuedtasks' doesn't exist
Update failed
Maintenance mode is kept active
```

IMHO the upgrade shouldn't stop if a deprecated table is not existing.

### PR DESCRIPTION
**Pull request by MorrisJobke**
* https://github.com/owncloud/core/commit/195c577c77b854723dc79e4baf19ad8d6b4d6d86
* fixes owncloud/core#18327
* fixes #90

cc @DeepDiver1975 @butonic @nickvergessen @LukasReschke Please review

@motlib Can you test if this fixes your upgrade issue?

@karlitschek This needs to be backported to stable8.1 because it fixes an upgrade failure.

### CODE REVIEW

File: appinfo/update.php [hunk 1]
```diff
@@ -1,18 +0,0 @@
...
- * This file is licensed under the Affero General Public License version 3 or
- * later. See the COPYING file.
- *
- * @author Jörn Friedrich Dreyer <jfd@butonic.de>
- * @copyright Jörn Friedrich Dreyer 2012-2015
- */
-
-$currentVersion = \OC::$server->getConfig()->getAppValue('search_lucene', 'installed_version');
-
-if (version_compare($currentVersion, '0.5.0', '<')) {
```
Comment (nickvergessen) [inline appinfo/update.php]: Could also wrap with a call to:
```php
	/**
	 * Check if a table exists
	 *
	 * @param string $table table name without the prefix
	 * @return bool
	 * @since 8.0.0
	 */
	public function tableExists($table);
```

Comment (MorrisJobke) [inline appinfo/update.php]: But it isn't really needed anymore. This is against master (-> means 8.2) and can even be backported to stable8.1, because the drop of the table is also in 8.1 of core. Why should we keep code that doesn't have any usecase?

**Comment by nazar-pc** [comment]
Just tested, works fine on ownCloud 8.1.1

**Comment by butonic** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@karlitschek Should I backport?

**Comment by karlitschek** [comment]
please backport

**Comment by MorrisJobke** [comment]
Backport is in #102
